const fs = require('fs');
let code = fs.readFileSync('src/components/LoanOfficerPortal.tsx', 'utf8');

const str1 = '                                       <button\\n                                         onClick={() => {\\n                                           setInitialOutreachLeadId(lead.id);\\n                                           setShowEmailOutreachModal(true);\\n                                         }}\\n                                         className="px-2.5 py-1 bg-[#C18C5D] hover:bg-[#a6764c] text-white font-bold text-[11px] rounded-lg flex items-center gap-1 transition-all shadow-2xs"\\n                                         title="Draft AI Outreach Email"\\n                                        >\\n                                          <Sparkles className="w-3 h-3" />\\n                                          <span>Draft AI Email</span>\\n                                        </button>';

const replacementStr = '                                       <button\\n                                         onClick={() => {\\n                                           setInitialOutreachLeadId(lead.id);\\n                                           setShowEmailOutreachModal(true);\\n                                         }}\\n                                         className="px-2.5 py-1 bg-[#C18C5D] hover:bg-[#a6764c] text-white font-bold text-[11px] rounded-lg flex items-center gap-1 transition-all shadow-2xs"\\n                                         title="Draft AI Outreach Email"\\n                                        >\\n                                          <Sparkles className="w-3 h-3" />\\n                                          <span>Draft AI Email</span>\\n                                        </button>\\n\\n                                        <button\\n                                          onClick={() => handleSalesforceSync(lead)}\\n                                          className="px-2.5 py-1 bg-blue-50 text-blue-700 hover:bg-blue-100 font-bold text-[11px] rounded-lg flex items-center gap-1 transition-all shadow-2xs border border-blue-200"\\n                                          title="Sync to Salesforce Enterprise"\\n                                        >\\n                                          <Cloud className="w-3 h-3" />\\n                                          <span>SF Sync</span>\\n                                        </button>';

code = code.replace(str1, replacementStr);

// Let's add the handleSalesforceSync function
const handleStr = '  const handleToggleLeadNurture = (leadId: string) => {';
const newHandleStr = '  const handleSalesforceSync = async (lead: CapturedLead) => {\\n    try {\\n      const user = auth.currentUser;\\n      if (!user) throw new Error("Must be logged in");\\n      \\n      const idToken = await user.getIdToken();\\n      const docSnap = await getDoc(doc(db, "user_integrations", user.uid));\\n      if (!docSnap.exists() || !docSnap.data().salesforceVault) {\\n        triggerToast("No Salesforce vault found. Please configure settings first.");\\n        setShowSalesforceSettings(true);\\n        return;\\n      }\\n\\n      triggerToast("Syncing to Salesforce...");\\n      const res = await fetch("/api/salesforce/sync-lead", {\\n        method: "POST",\\n        headers: { "Content-Type": "application/json", "Authorization": `Bearer ${idToken}` },\\n        body: JSON.stringify({\\n          salesforceVault: docSnap.data().salesforceVault,\\n          lead\\n        })\\n      });\\n      const data = await res.json();\\n      if (res.ok) {\\n        triggerToast(`Successfully synced to Salesforce! ID: ${data.salesforceId}`);\\n        const currentLeads = guidesState.leads || [];\\n        const updated = currentLeads.map(l => l.id === lead.id ? { ...l, salesforceId: data.salesforceId, salesforceSyncedAt: new Date().toISOString() } : l);\\n        onUpdateGuidesState({ ...guidesState, leads: updated });\\n      } else {\\n        triggerToast(`Sync failed: ${data.error}`);\\n      }\\n    } catch (e: any) {\\n      console.error(e);\\n      triggerToast(`Sync error: ${e.message}`);\\n    }\\n  };\\n\\n' + handleStr;

code = code.replace(handleStr, newHandleStr);

fs.writeFileSync('src/components/LoanOfficerPortal.tsx', code);
